language: cpp
compiler:
  - gcc
install: 
  - "sudo apt-get install libfftw3-dev libboost-all-dev make cmake "
  # the ubuntu ruby packages appear to be too old, so install via gem
  - gem install rdiscount
  - gem install hpricot
  - gem install mustache -v 0.99.6
  - gem install ronn
before_script:
  - mkdir build && cd build
  - cmake  -DBoost_NO_BOOST_CMAKE=ON ..
script:
  - make package
  - cpack -G DEB
after_success:
  - sudo dpkg -i scape-xcorrsound*deb
  - ls -l scape-xcorrsound*deb
  - overlap-analysis -h
  - sound-match -h
  - waveform-compare -h
